/* eslint-disable @typescript-eslint/no-explicit-any */
import type { UseFormSetValue } from "react-hook-form";

export function autoGenerateDiscountCodeForTextInput(
  setValue: UseFormSetValue<any>,
  maxlength: number,
  fieldName: string
) {
  const prefix = "SDQ-";
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let code = "";

  for (let i = 0; i < maxlength - prefix.length; i++) {
    const randomIndex = Math.floor(Math.random() * chars.length);
    code += chars[randomIndex];
  }

  setValue(fieldName, prefix + code);
}
